os: linux
dist: bionic
compiler: gcc

stages:
  - build
  - test

language: cpp
jobs:
  include:
    - stage: build
      script:
        - mkdir build && cd build
        - cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug .. && make
    - stage: test
      script:
        - mkdir build && cd build
        - cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug .. && make
        - make code_coverage
        - test/cpp-test
      
before_install:
  - pip install --user cpp-coveralls
install:
  - sudo apt-get install -y -qq lcov qt5-default libqt5charts5-dev
after_success:
  - coveralls --root .. --exclude test --exclude app/demo

