# We need a decent ubuntu dist
os: linux
dist: bionic

stages:
  - build
  - test

# Modern cpp settings from
#  http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
language: cpp
jobs:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
            - cmake-data
      env: COMPILER=g++-5
    - stage: build
      script:
        - export CXX=$COMPILER;
        - mkdir build
        - cd build
        - cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ../
        - make
        - make code_coverage
    - stage: test
      script:
        - test/cpp-test
      
before_install:
  - pip install --user cpp-coveralls
install:
  - sudo apt-get install -y -qq lcov qt5-default libqt5charts5-dev

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
